# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  identifier = "products"
  name = "Products"
  url = "products/"
  weight = 10

[[main]]
  identifier = "solutions"
  name = "Solutions"
  url = "solutions/"
  weight = 20

#[[main]]
#  identifier = "showcase"
#  name = "Showcase"
#  url = "showcase/"
#  weight = 30

[[main]]
  identifier = "support"
  name = "Support"
  url = "support/"
  weight = 40

[[main]]
  identifier = "company"
  name = "About"
  url = "company/"
  weight = 50


[[main]]
  parent = "products"
  name = "REDBACK VMS"
  url = "categories/redback/"
  weight = 10

[[main]]
  parent = "products"
  name = "Netwrok Video Recorder"
  url = "categories/nvr/"
  weight = 20

[[main]]
  parent = "products"
  name = "Central Monitoring System"
  url = "categories/cms/"
  weight = 30

[[main]]
  parent = "products"
  name = "Network Display Server"
  url = "categories/nds/"
  weight = 40
  
[[main]]
  parent = "products"
  name = "IP Camera"
  url = "categories/camera/"
  weight = 50

[[main]]
  parent = "products"
  name = "ETC"
  url = "categories/etc/"
  weight = 60

[[main]]
  parent = "solutions"
  name = "IP Video Wall"
  url = "solutions/ipwall/"
  weight = 10

[[main]]
  parent = "solutions"
  name = "Fingerprint Authentication"
  url = "solutions/fingerprint/"
  weight = 20

[[main]]
  parent = "solutions"
  name = "Safe Entry Vehicles"
  url = "solutions/entrance/"
  weight = 25

[[main]]
  parent = "solutions"
  name = "Smart NVR Failover"
  url = "solutions/failover/"
  weight = 30

[[main]]
  parent = "solutions"
  name = "Elevator CRT Integration"
  url = "solutions/elevator/"
  weight = 40

[[main]]
  parent = "solutions"
  name = "Abnormal Sound Detection"
  url = "solutions/sound/"
  weight = 50

[[main]]
  parent = "solutions"
  name = "License Plate Recognition"
  url = "solutions/lpr/"
  weight = 60

[[main]]
  parent = "solutions"
  name = "Thermal Imaging Camera"
  url = "solutions/thermal/"
  weight = 80

[[main]]
  parent = "solutions"
  name = "Flame / Smoke Detection"
  url = "solutions/fire/"
  weight = 90

[[main]]
  parent = "solutions"
  name = "Intrusion Detection"
  url = "solutions/intrusion/"
  weight = 100

[[main]]
  parent = "solutions"
  name = "Warning Broadcast"
  url = "solutions/broadcast/"
  weight = 110

[[main]]
  parent = "solutions"
  name = "Emergency Call"
  url = "solutions/emcall/"
  weight = 120

[[main]]
  parent = "support"
  name = "Software / Firmware"
  url = "support/software/"
  weight = 90

[[main]]
  parent = "support"
  name = "Supported IP Cameras"
  url = "support/cameras/"
  weight = 100

[[main]]
  parent = "support"
  name = "Online Manual"
  url = "https://emstone.gitbook.io/guide/basicguide"
  post = " &nbsp; <i class='fas fa-external-link-square-alt' aria-hidden='true'></i>"
  weight = 110

[[main]]
  parent = "company"
  name = "EMSTONE"
  url = "company/"
  weight = 10

#[[main]]
#  parent = "company"
#  name = "연혁"
#  url = "company/#history"
#  weight = 20

[[main]]
  parent = "company"
  name = "Contact"
  url = "company/#contact"
  weight = 30

#[[main]]
#  parent = "company"
#  name = "전국 지사"
#  url = "company/#branches"
#  weight = 40
