# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  identifier = "products"
  name = "Products"
  url = "products/"
  weight = 10

[[main]]
  identifier = "solutions"
  name = "Solutions"
  url = "solutions/"
  weight = 20

[[main]]
  identifier = "showcase"
  name = "Showcase"
  url = "showcase/"
  weight = 30

[[main]]
  identifier = "support"
  name = "Support"
  url = "support/"
  weight = 40

[[main]]
  identifier = "company"
  name = "Company"
  url = "company/"
  weight = 50
