# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  identifier = "products"
  name = "제품"
  url = "products/"
  weight = 10

[[main]]
  identifier = "solutions"
  name = "솔루션"
  url = "solutions/"
  weight = 20

[[main]]
  identifier = "showcase"
  name = "시공사례"
  url = "showcase/"
  weight = 30

[[main]]
  identifier = "support"
  name = "고객지원"
  url = "support/"
  weight = 40

[[main]]
  identifier = "company"
  name = "회사소개"
  url = "company/"
  weight = 50

[[main]]
  parent = "products"
  name = "REDBACK VMS"
  url = "categories/vms/"
  weight = 10

[[main]]
  parent = "products"
  name = "NVR / 하이브리드"
  url = "categories/nvr/"
  weight = 20

[[main]]
  parent = "products"
  name = "카메라"
  url = "categories/camera/"
  weight = 30

[[main]]
  parent = "products"
  name = "CMS 통합 모니터링"
  url = "categories/cms/"
  weight = 40

[[main]]
  parent = "products"
  name = "NDS 디스플레이 서버"
  url = "categories/nds/"
  weight = 50

[[main]]
  parent = "products"
  name = "PoE 앰프 / 비상벨"
  url = "categories/etc/"
  weight = 60

[[main]]
  parent = "solutions"
  name = "IP 비디오 월"
  url = "solutions/ipwall/"
  weight = 10

[[main]]
  parent = "solutions"
  name = "지문 인증"
  url = "solutions/fingerprint/"
  weight = 20

[[main]]
  parent = "solutions"
  name = "안전 입출차"
  url = "solutions/entrance/"
  weight = 25

[[main]]
  parent = "solutions"
  name = "NVR 장애 대응"
  url = "solutions/failover/"
  weight = 30

[[main]]
  parent = "solutions"
  name = "엘리베이터 CRT 연동"
  url = "solutions/elevator/"
  weight = 40

[[main]]
  parent = "solutions"
  name = "이상음원 감지"
  url = "solutions/sound/"
  weight = 50

[[main]]
  parent = "solutions"
  name = "차량번호 추출"
  url = "solutions/lpr/"
  weight = 60

[[main]]
  parent = "solutions"
  name = "열화상 카메라"
  url = "solutions/thermal/"
  weight = 80

[[main]]
  parent = "solutions"
  name = "화염 / 연기 감지"
  url = "solutions/fire/"
  weight = 90

[[main]]
  parent = "solutions"
  name = "출입 감지"
  url = "solutions/intrusion/"
  weight = 100

[[main]]
  parent = "solutions"
  name = "경고 방송"
  url = "solutions/broadcast/"
  weight = 110

[[main]]
  parent = "solutions"
  name = "비상벨"
  url = "solutions/emcall/"
  weight = 120

[[main]]
  parent = "showcase"
  name = "사이트 시공사례"
  url = "categories/site/"
  weight = 10

[[main]]
  parent = "showcase"
  name = "YouTube 채널"
  url = "https://www.youtube.com/channel/UC-4cLqYFsPtaOjtKolsKxRg"
  post = " &nbsp; <i class='fas fa-external-link-square-alt' aria-hidden='true'></i>"
  weight = 990

[[main]]
  parent = "showcase"
  name = "제품 사용사례"
  url = "categories/howto/"
  weight = 20

#[[main]]
#  parent = "support"
#  name = "인증 / 특허"
#  url = "support/certs/"
#  weight = 10

[[main]]
  parent = "support"
  name = "소프트웨어 / 펌웨어"
  url = "support/software/"
  weight = 90

[[main]]
  parent = "support"
  name = "IP 카메라 지원 목록"
  url = "support/cameras/"
  weight = 100

[[main]]
  parent = "support"
  name = "3rd party 연동 목록"
  url = "support/3rdparty/"
  weight = 110

[[main]]
  parent = "support"
  name = "EMSTONE HUB"
  url = "https://hub.emstone.com/"
  post = " &nbsp; <i class='fas fa-external-link-square-alt' aria-hidden='true'></i>"
  weight = 1000

[[main]]
  parent = "company"
  name = "엠스톤 소개"
  url = "company/"
  weight = 10

[[main]]
  parent = "company"
  name = "연혁"
  url = "company/#history"
  weight = 20

[[main]]
  parent = "company"
  name = "연락처"
  url = "company/#contact"
  weight = 30

[[main]]
  parent = "company"
  name = "전국 지사"
  url = "company/#branches"
  weight = 40
