# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  identifier = "products"
  name = "제품"
  url = "products/"
  weight = 10

[[main]]
  identifier = "solutions"
  name = "솔루션"
  url = "solutions/"
  weight = 20

[[main]]
  identifier = "showcase"
  name = "시공사례"
  url = "showcase/"
  weight = 30

[[main]]
  identifier = "support"
  name = "고객지원"
  url = "support/"
  weight = 40

[[main]]
  identifier = "company"
  name = "회사소개"
  url = "company/"
  weight = 50

[[main]]
  parent = "products"
  name = "NVR"
  url = "categories/nvr/"
  weight = 10

[[main]]
  parent = "products"
  name = "카메라"
  url = "categories/camera/"
  weight = 20

#[[main]]
#  parent = "products"
#  name = "CMS 스테이션"
#  url = "products/cms/"
#  weight = 30
#
#[[main]]
#  parent = "products"
#  name = "NDS 디스플레이 서버"
#  url = "products/nds/"
#  weight = 40
#
#[[main]]
#  parent = "products"
#  name = "기타"
#  url = "products/etc/"
#  weight = 50
#
[[main]]
  parent = "solutions"
  name = "IP 비디오 월"
  url = "solutions/wall/"
  weight = 10

[[main]]
  parent = "solutions"
  name = "지문 인증"
  url = "solutions/fingerprint/"
  weight = 20

[[main]]
  parent = "solutions"
  name = "안전 입출차"
  url = "solutions/entrance/"
  weight = 25

[[main]]
  parent = "solutions"
  name = "NVR 장애 대응"
  url = "solutions/failover/"
  weight = 3000

[[main]]
  parent = "solutions"
  name = "엘리베이터 CRT 연동"
  url = "solutions/elevator/"
  weight = 40

[[main]]
  parent = "solutions"
  name = "이상음원 감지"
  url = "solutions/sound/"
  weight = 50

[[main]]
  parent = "solutions"
  name = "차량번호 추출"
  url = "solutions/lpr/"
  weight = 60

[[main]]
  parent = "solutions"
  name = "열화상 카메라"
  url = "solutions/thermal/"
  weight = 80

[[main]]
  parent = "solutions"
  name = "화염 / 연기 감지"
  url = "solutions/fire/"
  weight = 90

[[main]]
  parent = "solutions"
  name = "PIR 센서 출입 감지"
  url = "solutions/intrusion/"
  weight = 100

[[main]]
  parent = "solutions"
  name = "경고 방송"
  url = "solutions/broadcast/"
  weight = 110

[[main]]
  parent = "solutions"
  name = "비상벨"
  url = "solutions/emergency/"
  weight = 120

[[main]]
  parent = "support"
  name = "IP 카메라 목록"
  url = "support/ip-cameras/"
  weight = 10

#[[main]]
#  parent = "support"
#  name = "자주 묻는 질문"
#  url = "support/#faq"
#  weight = 20
#
#[[main]]
#  parent = "support"
#  name = "튜토리얼"
#  url = "support/#tutorials"
#  weight = 30
#

[[main]]
  parent = "support"
  name = "YouTube 채널"
  url = "https://www.youtube.com/channel/UC-4cLqYFsPtaOjtKolsKxRg"
  post = "<i class='fas fa-external-link-alt align-middle float-right' aria-hidden='true'></i>"
  weight = 70

[[main]]
  parent = "support"
  name = "소프트웨어"
  url = "http://nvrsw.com/"
  post = "<i class='fas fa-external-link-alt align-middle float-right' aria-hidden='true'></i>"
  weight = 80

[[main]]
  parent = "support"
  name = "프로젝트 관리"
  url = "https://hub.nvrsw.com/"
  post = "<i class='fas fa-external-link-alt align-middle float-right' aria-hidden='true'></i>"
  weight = 90

[[main]]
  parent = "company"
  name = "엠스톤 소개"
  url = "company/"
  weight = 10

[[main]]
  parent = "company"
  name = "연혁"
  url = "company/#history"
  weight = 20

[[main]]
  parent = "company"
  name = "연락처"
  url = "company/#contact"
  weight = 30

[[main]]
  parent = "company"
  name = "전국 지사"
  url = "company/#branches"
  weight = 40
